# Generated by Django 5.0.4 on 2024-07-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
