# Generated by Django 5.0.4 on 2024-07-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_restaurant_menu_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
