# Generated by Django 5.0.4 on 2024-07-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
