# Generated by Django 5.0.4 on 2024-06-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
